// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package destination

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	ConfigAwsAccessKeyId     = "aws.accessKeyId"
	ConfigAwsBucket          = "aws.bucket"
	ConfigAwsRegion          = "aws.region"
	ConfigAwsSecretAccessKey = "aws.secretAccessKey"
	ConfigFormat             = "format"
	ConfigPrefix             = "prefix"
)

func (Config) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ConfigAwsAccessKeyId: {
			Default:     "",
			Description: "AWS access key id.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigAwsBucket: {
			Default:     "",
			Description: "the AWS S3 bucket name.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigAwsRegion: {
			Default:     "",
			Description: "the AWS S3 bucket region",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigAwsSecretAccessKey: {
			Default:     "",
			Description: "AWS secret access key.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigFormat: {
			Default:     "",
			Description: "the destination format, either \"json\" or \"parquet\".",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
				config.ValidationInclusion{List: []string{"parquet", "json"}},
			},
		},
		ConfigPrefix: {
			Default:     "",
			Description: "the S3 key prefix.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
	}
}
