// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package source

import (
	"github.com/conduitio/conduit-commons/config"
)

func (Config) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		"aws.accessKeyId": {
			Default:     "",
			Description: "AWS access key id.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		"aws.bucket": {
			Default:     "",
			Description: "the AWS S3 bucket name.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		"aws.region": {
			Default:     "",
			Description: "the AWS S3 bucket region",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		"aws.secretAccessKey": {
			Default:     "",
			Description: "AWS secret access key.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		"pollingPeriod": {
			Default:     "1s",
			Description: "polling period for the CDC mode, formatted as a time.Duration string.",
			Type:        config.ParameterTypeDuration,
			Validations: []config.Validation{},
		},
		"prefix": {
			Default:     "",
			Description: "the S3 key prefix.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
	}
}
